### ISSUE TITLE
Lack of read me and contributing guide

### ISSUE THREAD

**Issue by ximenesfel** [PointCloudLibrary/clang-bind#13]
Hi. I would like to help developing the python bindings. Looking at project repository (because this is a new project), it don't have a README.md and a contributing guide. At first I'm thinking to help with README.md for me become familiar with the project and later helping with the code. Do you have any guidance to write the README.me?

**Comment by kunaltyagi** [comment]
Thanks for pitching in.

There's some content in [discussion.md](https://github.com/PointCloudLibrary/clang-bind/blob/master/bindings/discussion.md) that might help you. Apart from that, not much to say. Do remember to include the following:
* dependencies required (found in the github actions)
* some basic commands that people can use to start contributing (base this on the cmake pr #11)

We can add more as we go on.

**Comment by ximenesfel** [comment]
@kunaltyagi Thanks for your response. I will look this references and start doing the README.md file.

**Comment by ximenesfel** [comment]
@kunaltyagi 

I managed to reproduce the steps informed in pr #11. The final result is a simple.cpp file located in pybind11-gen/src folder , that is the bind code. Is correct?

For clarification only, the main idea of this project is to generate the python bindings automatically without having to code each component. To do that we will follow the steps:

1) Build cpp project
2) Obtain a json representation
3) Generate python bind code from json represenation

Regarding dependencies required, looking the github actions I've found the following:

**black**
`pip install black`

**pytest**
`pip install pytest`

**libclang**
```
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
echo 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main' | sudo tee -a /etc/apt/sources.list
echo 'deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main' | sudo tee -a /etc/apt/sources.list
sudo apt-get update
sudo apt-get install -y libclang-11-dev python3-clang-11
```

Looking at CmakeLists.txt available in clang-bind/bindings/python folder, it seems in future we will have pcl and pybind11 as dependencies, but at the moment the dependencies are listed above.

**Comment by kunaltyagi** [comment]
Requirements for generating json or C++ code as per pybind11's format:
* libclang
* python3-clang-11

Requirements for generating the bindings as a module (not yet, but soon):
* mako
* requests
* conan
* cmake
* C++ compiler of choice

The following might not be a requirement if there is an internet connection:
* pybind11

Requirements for development:
* black

Requirements for testing:
* pytest

Please add a requirements.txt for all the python requirements. There's `python-cmake`

**Comment by kunaltyagi** [comment]
Closing this for the meantime. We can add a CONTRIBUTING.md later sometime
